version: 2

sources:
  - name: staging
    #database: "{{ env_var('DBT_DATABASE', 'taxi-rides-ny-339813-412521') }}"
    database: zoomcamp-de-452200
    #schema: "{{ env_var('DBT_SCHEMA', 'trips_data_all') }}"
    schema: trips_data_all
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata